- name: Help
  description: "Help page display this file"
  url: /help
  cmd: tail -n+6 config.yml

# Test url : http://localhost:8080/rainbow
- name: Rainbow
  description: "Test word highlights and stream"
  url: /rainbow
  cmd: ./tests/rainbow.sh
  # 'word' and 'line' support RegExp
  # 'class' could be any class define in public/css/custom.css
  highlight:
    # 'word' highlight only matching word
    - word: 'white'
      class: white
    - word: 'hide'
      class: hide
    - word: 'gray'
      class: gray
    - word: 'red'
      class: red
    - word: 'orange'
      class: orange
    - word: 'yellow'
      class: yellow
    - word: 'purple'
      class: purple
    - word: 'blue'
      class: blue
    - word: 'green'
      class: green
    # 'line' highlight only matching line
    - line: '0.1'
      class: yellow

# Test url : http://localhost:8080/args/test?hostname=foo&ip=192.168.0.1&mac=00:11:22:33:44:55
# Plain test url : http://localhost:8080/args/test/plain?hostname=foo&ip=192.168.0.1&mac=00:11:22:33:44:55
- name: Args
  description: "Test args, suburls, password and plain text"
  url: /args/test
  # Set a password to query url as "?password=suburlpass"
  password: suburlpass
  # Get /args/test/plain?hostname=foo&ip=192.168.0.1&mac=00:11:22:33:44:55&password=suburlpass
  # will be run as "./tests/args.sh foo 192.168.0.1 00:11:22:33:44:55"
  cmd: ./tests/args.sh {} {} {}
  args:
    - hostname
    - ip
    - mac
