---
- name: Help
  description: "Help page display this file"
  url: /help
  cmd: bat --plain --color always config.yml

- name: Rainbow
  description: "Test word highlights and stream"
  url: /rainbow
  cmd: ./tests/rainbow.sh
  # 'word' and 'line' support RegExp
  # 'class' could be any class define in public/css/custom.css
  highlight:
    # 'word' highlight only matching word
    - word: '^[0-9]+'
      class: bold
    - word: 'hide'
      class: hide
    # 'line' highlight only matching line
    - line: '10'
      class: italic

- name: Args
  description: "Test args, suburls, password and plain text"
  url: /args/test
  # Set a password to query url as "?password=suburlpass"
  password: suburlpass
  # Get /args/test/plain?hostname=foo&ip=192.168.0.1&mac=00:11:22:33:44:55&password=suburlpass
  # will be run as "./tests/args.sh foo 192.168.0.1 00:11:22:33:44:55"
  cmd: ./tests/args.sh "{hostname}" "{clientIp}" "{mac}" "{hostname} has ip {ip} and mac {mac}"
  args:
    - hostname
    - mac
