#!/bin/bash

echo -e "\n=> Test without authentication"
curl -i "http://localhost:3000/shellcast/args/test/plain?hostname=foo&ip=10.0.0.1&mac=00:11:22:33:44:55&password=suburlpass"
echo -e "\n => Test with authentication but no credentials"
curl -i "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n=> Test with valid x-remote-user authentication"
curl -i -H "X-Remote-User: remote_user1" "http://localhost:3000/shellcast/auth/plain"
echo -e "\n=> Test with NOT valid x-remote-user authentication"
curl -i -H "X-Remote-User: remote_userx" "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n=> Test with valid x-group authentication"
curl -i -H "X-Group: group1" "http://localhost:3000/shellcast/auth/plain"
echo -e "\n=> Test with NOT valid x-group authentication"
curl -i -H "X-Group: groupx" "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n=> Test with valid password authentication"
curl -i 'http://localhost:3000/shellcast/auth/plain?password=pa$$w0rd1'
echo -e "\n=> Test with NOT valid password authentication"
curl -i 'http://localhost:3000/shellcast/auth/plain?password=notvalidpa$$w0rd'
echo ""
echo -e "\n=> Test with valid basicauth authentication"
curl -i -u user1:password1 "http://localhost:3000/shellcast/auth/plain"
echo -e "\n=> Test with NOT valid USER basicauth authentication"
curl -i -u userx:notvalidpassword "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n=> Test with NOT valid PASSWORD basicauth authentication"
curl -i -u user1:notvalidpassword "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n=> Test with NOT authorized user basicauth authentication"
curl -i -u user2:password2 "http://localhost:3000/shellcast/auth/plain"
echo ""
echo -e "\n => Test with NOT valid mode"
curl -i "http://localhost:3000/shellcast/auth/"
echo ""
